# mysql数据库连接 省略
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test_staters?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 1qaz!QAZ


# mybatis的全局设置
mybatis-plus:
  # 别名扫描包，这样Mapper.xml中的每个语句的resultType就不用写全路径了
  type-aliases-package: com.myhexin.b2c.web.pojo
  # Mapper.xml扫描路径，然后在Mapper接口写上自定义方法并关联XML语句，即可实现手写SQL
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: on         #MyBatis-Plus驼峰转换，配置后不论手写SQL还是接口方法，都能自动映射（默认on）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     # mybatis输出日志
    # 全局设置：指定主键生成策略、以及逻辑删除字段的名称
  global-config:
    db-config:
      id-type: auto      # 全局指定主键的生成策略
      logic-delete-field: is_valid               # logic：逻辑
      logic-not-delete-value: 1
      logic-delete-value: 0